### ISSUE TITLE
New Unreal Version!

### ISSUE THREAD

**Issue by MTLPGaming** [nachomonkey/RefreshAllNodes#1]
I wanted to use your Plugin but the i noticed that it isn't "compatible" with UE 4.26.2...

I just wanted to let you know.

**Comment by nachomonkey** [comment]
Nothing in the patch versions should break compatibility with this plugin. So, my bad, I should not have mentioned the patch versions in the compatibility list.

The plugin is fully compatible with UE 4.26.2

I will update it so it says "UE 4.26.x" as opposed to "UE 4.26.1"

**Comment by MTLPGaming** [comment]
Thank You!
