### ISSUE TITLE
5.4.1 fails to compile

### ISSUE THREAD

**Issue by jazzman170** [nachomonkey/RefreshAllNodes#10]
Using source unreal engine 5.4.1, this plugin now fails to compile :(

**Comment by nachomonkey** [comment]
Hello @jazzman170-

Thank you for posting.
I've tested RefreshAllNodes on UE 5.4.1, and I didn't notice any problems.

Are there any specific compilation errors?

Besides there being an error in the plugin's code, the most likely problem is that you don't have Unreal Engine set up with Visual Studio.
[Setting up Visual Studio - Unreal Engine documentation](https://dev.epicgames.com/documentation/en-us/unreal-engine/setting-up-visual-studio-development-environment-for-cplusplus-projects-in-unreal-engine)

I've released a compiled version of this plugin for UE 5.4.1. You could give it a try, but if you've built UE 5.4.1 from source then I doubt it'll help:
https://github.com/nachomonkey/RefreshAllNodes/releases/download/v1.5%2BUE5.4.1/RefreshAllNodes-1.5-UE5.4.1.zip

**Comment by nachomonkey** [comment]
^^^
Sorry- When I had posted that, the "5.4.1" binaries had been unwittingly compiled with UE 5.3.0.

I have just now updated the precompiled version so it's now compiled with UE 5.4.1.
Same download link:
https://github.com/nachomonkey/RefreshAllNodes/releases/download/v1.5%2BUE5.4.1/RefreshAllNodes-1.5-UE5.4.1.zip

**Comment by jazzman170** [comment]
Thanks for the update! Gonna give it a go now! This plugin has saved me on many occasions. I have times where multiple blueprints fail to compile because something else isnt compiled or had an error and it breaks 10 other blueprints. it can be very stressful to figure out which one broke but this plugin has never failed me once!
