### ISSUE TITLE
UE 5.4.1 pre compiled not working.

### ISSUE THREAD

**Issue by Cmcginniss** [nachomonkey/RefreshAllNodes#11]
says the following modules are missing or built different engine.       Asks to rebuild and fails to rebuild

**Comment by nachomonkey** [comment]
My apologies, I had launched the wrong Unreal Engine- the "5.4.1" binaries were compiled with UE 5.3.0.  :man_facepalming:

Please try it now. I have updated the precompiled version and it is now truly compiled with UE 5.4.1.

https://github.com/nachomonkey/RefreshAllNodes/releases/download/v1.5%2BUE5.4.1/RefreshAllNodes-1.5-UE5.4.1.zip

**Comment by nachomonkey** [comment]
Thank you, glad it helps :tada:
