### ISSUE TITLE
Features missing in UE 5.0.3

### ISSUE THREAD

**Issue by XanaGA** [nachomonkey/RefreshAllNodes#4]
Hi, I'm using the plugin in UE 5.0.3, but I only see the option of refreshing all the nodes from all the blueprints:
![refresh_working](https://user-images.githubusercontent.com/88030501/180405619-59d10226-9921-4bd1-9e2e-a3c6830408bb.png)

I can't do it in single BP or folders. The following is the result of right-clicking on a folder:
![refresh_folder](https://user-images.githubusercontent.com/88030501/180406403-872a7d5f-54b9-49a9-b478-c4fdfa75d910.png)

I also can't find the option of automatically compile after refreshing in "Projects settings":
![refresh_ps](https://user-images.githubusercontent.com/88030501/180406988-18ac66e6-0c44-451b-88a1-aa753c131e9a.png)

Am I doing something wrong? In case it is helpful here I describe what I did for installing the plugin

- I've downloaded the .tar.gz file from [here](https://github.com/nachomonkey/RefreshAllNodes/releases/tag/v1.2-UE5EA2)
- Extracted and moved the result to the Plugins folder
- Downloaded the 3 files **UnrealEditor-RefreshAllNodes.dll**, **UnrealEditor-RefreshAllNodes.pdb**, **UnrealEditor.modules**, from the same [link](https://github.com/nachomonkey/RefreshAllNodes/releases/tag/v1.2-UE5EA2).
- Moved those files to the Plugins\RefreshAllNodes-1.2-UE5EA2\Binaries\Win64. Also trying to make it work I've removed the previous UE4 files that were there, but I didn't solve the issue.

Did I missed something?

**Comment by nachomonkey** [comment]
You did nothing wrong. Those features were added in version 1.3, and I hadn't released the binaries for that version yet. I just built the new binaries and released them. So it should work now :)

    I can't do it in single BP or folders

Version 1.3 lets you refresh the blueprints in a folder via the context menu in the content browser, but I will note that you cannot do it to single blueprints-- if you need to do it to just one blueprint then you can just open the blueprint and run "Refresh All nodes" from under the File menu at the top (that's built into UE by default). :)

Hope it helps :)

**Comment by XanaGA** [comment]
I think the .zip and .tar files from the release 1.3 were not build. At least the Binaries folder doesn't appear in my case.

**Comment by nachomonkey** [comment]
I'm very for the inconvenience-- I had built that last release incorrectly.

Please try the latest release, it should be easier and work cleanly :)

**Comment by XanaGA** [comment]
Great. now it is just straightforward! Super simple, thank you :)
