### ISSUE TITLE
Unreal Engine 5.3.1

### ISSUE THREAD

**Issue by oldmanroshi** [nachomonkey/RefreshAllNodes#8]
Hello, will RefreshAllNodes version 5.3 work on Unreal Engine 5.3.1 (just released)?  I did not want to chance it.  If not just letting you know there was an update.  Thank you and amazing plugin.

**Comment by nachomonkey** [comment]
I haven't tested RefreshAllNodes with UE 5.3.1 yet, but it shouldn't make a difference. The last time I actually changed the plugin's code was for UE 5.1, almost a year ago when some big Unreal Editor API changes made it so it wouldn't compile.

I have been releasing builds for each new UE version- I do that just for users who don't have C++ compilation set up with UE. If you can compile it yourself then go for it.

There's no harm in trying RefreshAllNodes on UE 5.3.1; 90% chance the plugin code will still compile. But there's no chance it'll malfunction and break your project.
I can release a compiled build soon in case it's needed.

And thank you, I'm glad it's been helpful!
