### ISSUE TITLE
About 1,000 blueprints freeze and crash.

### ISSUE THREAD

**Issue by elstp** [nachomonkey/RefreshAllNodes#9]
In the latest version of the 5.3 engine compiled by myself, after refreshing all nodes and about 1,000 blueprints, the editor got stuck and crashed.

**Comment by nachomonkey** [comment]
Sorry about the crashing. My plugin loading so many blueprints probably is stretching the resources of your computer too far. Attempting to fix that would involve a deep dive into Unreal Engine's memory management system. That is beyond the scope of this project.

You could try to limit the amount of blueprints being refreshed by right-clicking a specific folder in the Content Browser and using "Refresh Blueprints" from there. Or consider excluding some of your blueprint paths in the plugin's settings.

**Comment by elstp** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。
